### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by 0604hx** [codelibs/elasticsearch-fess-suggest#1]
I install this plugin on my ES (1.7.1), and then I run localhost:9200/music/_fsuggest/create, I had got music.suggest index created.

but I could not get what I wanted while using /_fsuggest?q= 

exception stack ：：
org.elasticsearch.search.SearchParseException: [music.suggest][3]: from[-1],size[10]: Parse Failure [Failed to parse source [{"size":10,"query":{"function_score":{"query":{"query_string":{"query":"reading_0:１２\* OR reading_0:イチニ\* OR reading_0:12\* OR reading_0:itini\* OR reading_0:ichini_","default_operator":"and","analyze_wildcard":false}},"functions":[{"filter":{"query":{"query_string":{"query":"text:12_","default_operator":"and","analyze_wildcard":false}}},"weight":2.0},{"field_value_factor":{"field":"score","factor":1.0}}]}},"post_filter":{"query":{"query_string":{"query":"roles:_guest_"}}},"sort":[{"_score":{"order":"desc"}},{"score":{"order":"desc"}}]}]]
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
    at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
    at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
    at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchException: Unable to find a field mapper for field [score]
    at org.elasticsearch.index.query.functionscore.fieldvaluefactor.FieldValueFactorFunctionParser.parse(FieldValueFactorFunctionParser.java:89)
    at org.elasticsearch.index.query.functionscore.FunctionScoreQueryParser.parseFiltersAndFunctions(FunctionScoreQueryParser.java:217)
    at org.elasticsearch.index.query.functionscore.FunctionScoreQueryParser.parse(FunctionScoreQueryParser.java:122)
    at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:305)
    at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
    at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
    at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
    at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)

**Comment by marevol** [comment]
Did you use .../_fsuggest/update when inserting data?
